# Generated by Django 4.1.7 on 2023-11-19 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_doc', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'documentos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cnpj', models.CharField(db_column='CNPJ', max_length=80)),
                ('ie', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('endereco', models.CharField(max_length=100)),
                ('fone', models.CharField(max_length=30)),
                ('responsavel', models.CharField(max_length=80)),
                ('data_inicio', models.DateField()),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cnpj', models.CharField(db_column='CNPJ', max_length=80)),
                ('ie', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('endereco', models.CharField(max_length=80)),
                ('fone', models.CharField(max_length=30)),
                ('responsavel', models.CharField(max_length=80)),
                ('data_cadastro', models.DateField()),
            ],
            options={
                'db_table': 'fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Frotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_frota', models.CharField(max_length=20)),
                ('fk_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresas')),
            ],
            options={
                'db_table': 'frotas',
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cpf', models.CharField(db_column='CPF', max_length=50)),
                ('pis', models.CharField(db_column='PIS', max_length=30)),
                ('data_admissao', models.DateField()),
                ('data_demissao', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=90)),
                ('funcao', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('pais', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'localidades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlanoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=20)),
                ('subconta', models.IntegerField()),
                ('sigla_situacao', models.CharField(max_length=1)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
            options={
                'db_table': 'plano_contas',
            },
        ),
        migrations.CreateModel(
            name='Situacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nome', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'situacoes',
            },
        ),
        migrations.CreateModel(
            name='TiposVeiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_veiculo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipos_veiculos',
            },
        ),
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('placas', models.CharField(max_length=80)),
                ('datacompra', models.DateField(db_column='dataCompra')),
                ('tipo_aquisicao', models.CharField(max_length=50)),
                ('km_inicial', models.IntegerField()),
                ('fk_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresas')),
                ('fk_frota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.frotas')),
                ('fk_situacoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.situacoes')),
                ('fk_tipo_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tiposveiculos')),
            ],
            options={
                'db_table': 'veiculos',
            },
        ),
        migrations.CreateModel(
            name='LancarViagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crtc', models.CharField(max_length=30)),
                ('data', models.DateField()),
                ('kmfinal', models.IntegerField(db_column='kmFinal')),
                ('kminicial', models.IntegerField(db_column='kmInicial')),
                ('litragem', models.FloatField()),
                ('qtdeveiculos', models.IntegerField()),
                ('fk_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.localidades')),
                ('fk_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresas')),
                ('fk_frota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.frotas')),
                ('fk_motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionarios')),
            ],
            options={
                'db_table': 'lancar_viagens',
            },
        ),
        migrations.CreateModel(
            name='LancarFinanceiroViagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('historico', models.CharField(max_length=100)),
                ('fk_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documentos')),
                ('fk_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresas')),
                ('fk_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fornecedores')),
                ('fk_lancar_viagens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lancarviagens')),
                ('fk_plano_contas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planocontas')),
            ],
            options={
                'db_table': 'lancar_financeiro_viagens',
            },
        ),
        migrations.CreateModel(
            name='LancarFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ano_referente', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('fk_funcionarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionarios')),
            ],
            options={
                'db_table': 'lancar_ferias',
            },
        ),
        migrations.CreateModel(
            name='LancarContabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('historico', models.CharField(max_length=100)),
                ('fk_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documentos')),
                ('fk_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresas')),
                ('fk_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fornecedores')),
                ('fk_plano_contas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planocontas')),
                ('fk_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculos')),
            ],
            options={
                'db_table': 'lancar_contabilidade',
            },
        ),
        migrations.CreateModel(
            name='LancarBaixaVeiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField()),
                ('km_final', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('comprador', models.CharField(max_length=60)),
                ('telefone_comprador', models.CharField(max_length=40)),
                ('fk_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculos')),
            ],
            options={
                'db_table': 'lancar_baixa_veiculos',
            },
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='fk_localidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.localidades'),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='fk_situacoes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.situacoes'),
        ),
        migrations.AddField(
            model_name='frotas',
            name='fk_situacoes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.situacoes'),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='fk_localidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.localidades'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='fk_localidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.localidades'),
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cnpj', models.CharField(db_column='CNPJ', max_length=60)),
                ('ie', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=60)),
                ('data_cadastro', models.DateField()),
                ('fk_localidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.localidades')),
            ],
            options={
                'db_table': 'clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AcertosViagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('historico', models.CharField(max_length=100)),
                ('fk_lancar_viagens', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.lancarviagens')),
                ('fk_plano_contas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planocontas')),
            ],
            options={
                'db_table': 'acertos_viagens',
                'managed': True,
            },
        ),
    ]
