# Generated by Django 4.2.16 on 2024-10-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acertosviagens',
            name='km_final',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lancarbaixaveiculos',
            name='km_final',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lancarferias',
            name='ano_referente',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lancarviagens',
            name='litragem',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='lancarviagens',
            name='qtdeveiculos',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='planocontas',
            name='conta',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='planocontas',
            name='subconta',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='ano',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='km_inicial',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='renavam',
            field=models.IntegerField(blank=True),
        ),
    ]
