# Generated by Django 4.1.7 on 2023-11-19 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_acertosviagens_fk_lancar_viagens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acertosviagens',
            options={},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documentos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='localidades',
            options={},
        ),
    ]
