# Generated by Django 4.2.16 on 2024-10-17 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_acertosviagens_acertoviagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fk_cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fk_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estado'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='fk_cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cidade'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='fk_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estado'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='fk_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pais'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fk_cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cidade'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fk_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estado'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='fk_cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cidade'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='fk_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estado'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='fk_cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cidade'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='fk_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estado'),
        ),
        migrations.AlterField(
            model_name='origem',
            name='fk_cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cidade'),
        ),
        migrations.AlterField(
            model_name='origem',
            name='fk_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estado'),
        ),
        migrations.AlterField(
            model_name='origem',
            name='fk_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pais'),
        ),
    ]
