# Generated by Django 4.2.16 on 2024-10-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cliente_fk_cidade_alter_cliente_fk_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='origem',
            old_name='fk_cidade',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='origem',
            old_name='fk_estado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='origem',
            old_name='fk_pais',
            new_name='pais',
        ),
    ]
