# Generated by Django 3.1.5 on 2024-10-24 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20241020_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acertoviagem',
            name='fk_forma_pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.formapagamento'),
        ),
        migrations.AlterField(
            model_name='acertoviagem',
            name='fk_lancar_viagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lancarviagem'),
        ),
        migrations.AlterField(
            model_name='acertoviagem',
            name='fk_plano_conta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.planoconta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fk_cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fk_estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estado'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='fk_cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cidade'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='fk_estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estado'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='fk_pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pais'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fk_cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cidade'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fk_estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estado'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='fk_cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cidade'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='fk_estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estado'),
        ),
        migrations.AlterField(
            model_name='frota',
            name='fk_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='frota',
            name='fk_situacoes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.situacao'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='fk_cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cidade'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='fk_estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estado'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='fk_funcao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcao'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='fk_situacoes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.situacao'),
        ),
        migrations.AlterField(
            model_name='lancarbaixaveiculo',
            name='fk_veiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.veiculo'),
        ),
        migrations.AlterField(
            model_name='lancarcontabilidade',
            name='fk_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.documento'),
        ),
        migrations.AlterField(
            model_name='lancarcontabilidade',
            name='fk_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='lancarcontabilidade',
            name='fk_fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor'),
        ),
        migrations.AlterField(
            model_name='lancarcontabilidade',
            name='fk_plano_conta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.planoconta'),
        ),
        migrations.AlterField(
            model_name='lancarcontabilidade',
            name='fk_veiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.veiculo'),
        ),
        migrations.AlterField(
            model_name='lancardocveiculo',
            name='fk_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='lancardocveiculo',
            name='fk_veiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.veiculo'),
        ),
        migrations.AlterField(
            model_name='lancarferias',
            name='fk_funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcionario'),
        ),
        migrations.AlterField(
            model_name='lancarfinanceiroviagem',
            name='fk_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.documento'),
        ),
        migrations.AlterField(
            model_name='lancarfinanceiroviagem',
            name='fk_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='lancarfinanceiroviagem',
            name='fk_fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor'),
        ),
        migrations.AlterField(
            model_name='lancarfinanceiroviagem',
            name='fk_lancar_viagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lancarviagem'),
        ),
        migrations.AlterField(
            model_name='lancarfinanceiroviagem',
            name='fk_plano_conta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.planoconta'),
        ),
        migrations.AlterField(
            model_name='lancarviagem',
            name='fk_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.destino'),
        ),
        migrations.AlterField(
            model_name='lancarviagem',
            name='fk_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='lancarviagem',
            name='fk_frota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.frota'),
        ),
        migrations.AlterField(
            model_name='lancarviagem',
            name='fk_motorista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcionario'),
        ),
        migrations.AlterField(
            model_name='lancarviagem',
            name='fk_origem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.origem'),
        ),
        migrations.AlterField(
            model_name='origem',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cidade'),
        ),
        migrations.AlterField(
            model_name='origem',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estado'),
        ),
        migrations.AlterField(
            model_name='origem',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pais'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='fk_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='fk_frota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.frota'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='fk_situacoes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.situacao'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='fk_tipo_veiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoveiculo'),
        ),
    ]
